# BROKER MOSQUITTO
CFREIRE_FEED = "cfreire/feeds/1/#"
CFREIRE_IP = '35.204.77.82'
CFREIRE_PORT = 1883

# REDIS
REDIS_SERVER = "redis"
REDIS_DB_DEFAULT = 0
REDIS_DB_DEV = 1
REDIS_PORT = 6379

# DATABASE
MONGO_SERVER = "mongodb://mongo:27017/"
MONGO_DATABASE_DEFAULT = 'iot'

